### ISSUE TITLE
About erl merging threshold and the challenge timeline

### ISSUE THREAD

**Issue by Levishery** [PytorchConnectomics/AxonEM-challenge#3]
Hello,

According to the paper, the original ERL is extended with a “tolerance” threshold. Is it implemented through the parameter merging threshold? If it's true, I found the explanation of this parameter confusing in [https://github.com/PytorchConnectomics/AxonEM-challenge/blob/main/challenge_eval/eval_erl.py](url). 

BTW, when will the challenge timeline come out?

Thanks!

**Comment by donglaiw** [comment]
Thank you for your feedback!
- We modify Funke lab's ERL computation with an extra argument `merge_thres` which is set to 50 to alleviate the effect of skeletonization outliers. https://github.com/PytorchConnectomics/funlib.evaluate/blob/master/funlib/evaluate/run_length.py#L212

- Sorry for the delay. We are testing out the docker and it'll be ready in a day or two. will keep you posted
